# Generated by Django 4.0.1 on 2022-01-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0006_empleado_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Empleado', verbose_name='Imagen'),
        ),
    ]
